# This workflow integrates ShiftLeft NG SAST with GitHub
# Visit https://docs.shiftleft.io for help
name: ShiftLeft

on:
  pull_request:
  workflow_dispatch:
  push:
  # We recommend triggering a scan when merging to your default branch as a best practice,
  # especially if you'd like to compare the results of two scans (e.g., a feature branch against the
  # default branch)
    branches:
      - main
      - master
jobs:
  NG-SAST-Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # We are building this application with Java 11
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11.0.x
    - name: Package with maven
      run: mvn compile package
    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    # ShiftLeft requires Java 1.8. Post the package step override the version
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: NextGen Static Analysis
      run: ${GITHUB_WORKSPACE}/sl analyze --wait --app Vulnado2 --tag branch={{`${{ github.head_ref }}`}} --vcs-prefix-correction "com/scalesec=src/main/java/com/scalesec" --java --cpg target/vulnado-0.0.1-SNAPSHOT.jar

      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: HTTP Request Action
      id: myRequest
        # You may pin to the exact commit or the version.
        # uses: fjogeleit/http-request-action@0929a0c636cc8dc6ba7715f5b3d90b0655ded3d7
      uses: fjogeleit/http-request-action@v1.8.0
      with:
        # Request URL
        url: 'https://www.shiftleft.io/api/v4/orgs/4a8c4823-84da-4a6c-b42a-2088bf8de419/apps/Vulnado2/findings?severity=critical'
        # Request Method
        method: 'GET'
        # Content Type
        # contentType: # optional
        # Request Body as JSON String
        # data: # optional, default is {}
        # Map of absolute file paths as JSON String
        # files: # optional, default is {}
        # Auth Username
       #  username: # optional
        # Auth Password
        # password: # optional
        # Request Timeout in Sec
        # timeout: # optional, default is 5000
        # Bearer Authentication Token
        bearerToken: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }} # optional
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        
    - name: Show Response
      run: echo ${{ steps.myRequest.outputs.response }}

